### ISSUE TITLE
"Joyeux anniversaire dans tous les recoins " de Perceval 

### ISSUE THREAD

**Issue by Neirda24** [kaamelott-gifboard/kaamelott-gifboard#74]
Voir la vidéo ci contre : https://youtu.be/VzpIjs0xfbs?si=0eB-aFOGvrzWtER2

Merci pour ce travail essentiel et formidable. On peut désormais faire une conversation intégralement rien qu'avec des gif.

**Comment by Zayon** [comment]
Salut, merci pour ton message ça fait toujours plaisir de savoir que notre site plait 😊

Cela fait un moment que nous n'avons pas ajoutés de gifs sur le site, le setup de génération des gifs est un peu complexe 😅

On laisse l'issue ouverte et on y répondra en priorité lorsqu'on reprendra du service.

**Comment by Neirda24** [comment]
Si le setup est dans le code je peux y jeter un oeil.

**Comment by VinceTommasi** [comment]
Hello @Neirda24 ! Le gif est dispo ici : https://kaamelott-gifboard.fr/gif/c-est-l-anniversaire-dans-tous-les-recoins :partying_face: 

Je close l'issue, merci encore pour ton message ! :)
