### ISSUE TITLE
Accelaration du chargement des gifs

### ISSUE THREAD

**Issue by narsha-io** [kaamelott-gifboard/kaamelott-gifboard#78]
Bonjour (Merci pour votre projet vous refaites mes journées)

J'imagine que ça dépend de l'endroit où vous hostés votre projet (probablement en France) et de la localisation des visiteurs mais de chez moi en Asie c'est plus rapide de charger vos gifs depuis les liens github que depuis votre site web.

**Comment by VinceTommasi** [comment]
Hello @narsha-io ! Merci pour ton message :)

En effet notre serveur est bien hebergé en France uniquement et nous n'avons pas (encore ? :stuck_out_tongue: ) la puissance de frappe pour égaler Github et servir les gifs partout dans le monde. Du moins pas avec ce que rapporte le site, autrement dit 0€ ahah.

Peut-être un jour qui sait :crossed_fingers: désolé en tout cas pour le moment nous n'avons pas de solutions :(

**Comment by narsha-io** [comment]
Merci @VinceTommasi pour le retour je me doutais bien. 
Je ne connais pas votre "philosophie" au niveau du code, mais p-e vous pouvez faire des liens vers les images github a la place (apres c'est p-e beaucoup de travail pour un pégueux comme moi ^^)
